### ISSUE TITLE
load_ibama: status was 'SSL peer certificate or SSH remote key was not OK'

### ISSUE THREAD

**Issue by MatthieuStigler** [datazoompuc/datazoom.amazonia#107]
Hi

Thanks for this great package! I am getting an error when downloading, not sure whether it is R- or package-specific... 

Workaround I found, from [here](https://stackoverflow.com/questions/69716835/turning-ssl-verification-off-inside-download-file/69718474#69718474), was to use: `options(download.file.method="curl", download.file.extra="-k -L")`

Problem (using R 4.2)

``` r
library(datazoom.amazonia)

data <- load_ibama(dataset = "areas_embargadas", raw_data = FALSE, 
                   language = "eng", legal_amazon_only = FALSE)
#> Warning in utils::download.file(url = path, destfile = temp, mode =
#> "wb"): URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/
#> downloadListaAreasEmbargadas.php': status was 'SSL peer certificate or SSH
#> remote key was not OK'
#> Error in utils::download.file(url = path, destfile = temp, mode = "wb"): cannot open URL 'https://servicos.ibama.gov.br/ctf/publico/areasembargadas/downloadListaAreasEmbargadas.php'
```

<sup>Created on 2022-06-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by FredieDidier** [comment]
Hi Mr Stigler, good morning. Firstly, thanks for you insightful suggestion!
 I have just tried to download it using our original code and it worked for me under this R 4.2 version. Could you double check to see if this applies to you?

**Comment by IgorRigolon** [comment]
Hey @MatthieuStigler, thanks for the confirmation. I found out that I was having the same problem you reported and it also persisted for me.

Since we have other functions that use curl, I just changed the method to "curl" and it was enough to solve the problem for me. I'd like to make sure the problem is also gone for you before introducing the changes though.

If you want to test it, download the updated version from this new branch using

`devtools::install_github("datazoompuc/datazoom.amazonia", ref = "ibama_download")`

Then your previous code should hopefully work. Thank you for going the extra mile looking for solutions, and please let us know if this fixes it.
